### ISSUE TITLE
15998번 - 카카오머니

### ISSUE THREAD

**Issue by dongkii** [fubabaz/algorithm#384]
https://www.acmicpc.net/problem/15998

**Comment by zeroradish** [comment]
🏆 **zeroradish**   Memory 95,260KB [코드보기](https://github.com/fubabaz/algorithm/pull/388/files)
🏆 **hwangdj**  Time 552ms [코드보기](https://github.com/fubabaz/algorithm/pull/387/files)
🏆 **hwangdj**   Short Code 1,342B [코드보기](https://github.com/fubabaz/algorithm/pull/387/files)
