### ISSUE TITLE
1074번 - Z

### ISSUE THREAD

**Issue by j-s-leee** [fubabaz/algorithm#389]
https://www.acmicpc.net/problem/1074

**Comment by zeroradish** [comment]
:trophy: **qsdd0122**  Memory 11,508KB [코드보기](https://github.com/fubabaz/algorithm/pull/394/files)
:trophy: **qsdd0122**  Time 80ms [코드보기](https://github.com/fubabaz/algorithm/pull/394/files)
:trophy: **dgyang**  Short Code 402B [코드보기](https://github.com/fubabaz/algorithm/pull/390/files)
