### ISSUE TITLE
2659번 - 십자카드 문제

### ISSUE THREAD

**Issue by dongkii** [fubabaz/algorithm#395]
https://www.acmicpc.net/problem/2659

**Comment by zeroradish** [comment]
🏆  **dongkii** Memory 14,300KB [코드보기](https://github.com/fubabaz/algorithm/pull/396/files)
🏆  **dongkii**  Time 124ms [코드보기](https://github.com/fubabaz/algorithm/pull/396/files)
🏆  **dongkii**  Short Code 503B [코드보기](https://github.com/fubabaz/algorithm/pull/396/files)
