### ISSUE TITLE
3019번 - 테트리스

### ISSUE THREAD

**Issue by djun9512** [fubabaz/algorithm#400]
https://www.acmicpc.net/problem/3019

**Comment by zeroradish** [comment]
:trophy: [dongkii](https://github.com/dongkii)  Memory 11,532KB [코드보기](https://github.com/fubabaz/algorithm/pull/401/files)
:trophy: [dongkii](https://github.com/dongkii)  Time 64ms [코드보기](https://github.com/fubabaz/algorithm/pull/401/files)
:trophy: [dongkii](https://github.com/dongkii)  Short Code 1,064B [코드보기](https://github.com/fubabaz/algorithm/pull/401/files)
