### ISSUE TITLE
1254번 - 팰린드롬 만들기

### ISSUE THREAD

**Issue by dongkii** [fubabaz/algorithm#408]
https://www.acmicpc.net/problem/1254

**Comment by zeroradish** [comment]
👴🏻

**Comment by zeroradish** [comment]
:trophy: <img class="avatar avatar-user" src="https://avatars.githubusercontent.com/u/31609765?s=52&amp;v=4" width="26" height="26" alt="@dongkii">  Memory 11,436KB [코드보기](https://github.com/fubabaz/algorithm/pull/401/files)
:trophy: <img class="avatar avatar-user" src="https://avatars.githubusercontent.com/u/28586265?s=52&amp;v=4" width="26" height="26" alt="@zeroradish">  Time 68ms [코드보기](https://github.com/fubabaz/algorithm/pull/404/files)
:trophy: <img class="avatar avatar-user" src="https://avatars.githubusercontent.com/u/28586265?s=52&amp;v=4" width="26" height="26" alt="@zeroradish">  Short Code 384B [코드보기](https://github.com/fubabaz/algorithm/pull/404/files)
