### ISSUE TITLE
1912번 - 연속합

### ISSUE THREAD

**Issue by yeony721** [fubabaz/algorithm#414]
https://www.acmicpc.net/problem/1912

**Comment by zeroradish** [comment]
:trophy:@dongkii Memory 21,244KB [코드보기](https://github.com/fubabaz/algorithm/pull/416/files)
:trophy:@dongkii Time 160ms [코드보기](https://github.com/fubabaz/algorithm/pull/416/files)
:trophy:@zeroradish Short Code 464B [코드보기](https://github.com/fubabaz/algorithm/pull/418/files)
