### ISSUE TITLE
25239번 - 가희와 카오스 파풀라투스

### ISSUE THREAD

**Issue by djun9512** [fubabaz/algorithm#420]
https://www.acmicpc.net/problem/25239

**Comment by zeroradish** [comment]
:trophy: @j-s-leee Memory 18,872KB [코드보기](https://github.com/fubabaz/algorithm/pull/419/files)
:trophy: @j-s-leee  Time 236ms [코드보기](https://github.com/fubabaz/algorithm/pull/419/files)
